//for G-maze
var shuffleSequence = seq("q_intro_prolificid",
	"evlab_intro_instructions",
	"q_intro_country", "q_intro_language", "q_intro_age",
	"intro-gram",
	"intro-practice", followEachWith("sep", "practice"),
	"end-practice",
	//Run ALL the items that start with "crit_item" in random order, separated by "sep"
	//followEachWith("sep", randomize(anyOf(startsWith("crit")))),
	followEachWith("sep", rshuffle("crit_item")),

	//"end-practice", followEachWith("sep",randomize(anyOf(startsWith("rel"),startsWith("and"), startsWith("adverb"), startsWith("filler")))),
	"end-experiment");

var showProgressBar = false;

var defaults = [
    //"Maze", {redo: true, rmess: "Incorrect. Please try again!", time: 0}, //uncomment to try "redo" mode old-style without delay
    //"Maze", {redo: true}, //uncomment to try Maze with new redo mode with a delay!
];
var items = [
	["q_intro_prolificid", "Form", {html: "<p>Please enter your Prolific ID:</p><p><input type='text' name='prolificid' size='24' /></p>", continueMessage: "Continue"}],

	["evlab_intro_instructions", "Message", {html: "<p>You are participating in a study about language and related cognitive abilities being conducted by Professor Evelina Fedorenko from the Department of Brain and Cognitive Sciences at MIT. If you have questions or concerns, you can contact Professor Fedorenko by email (evelina9@mit.edu)</p><p>Your participation in this research is voluntary. You may decline to answer any or all of the following questions. You may decline further participation, at any time, without adverse consequences. Your anonymity is assured; the researchers who have requested your participation will not receive any personal information about you.\n</p><p>Please answer the background questions below. The only restriction to being paid is achieving the accuracy requirements as detailed below XXXXXXXXXXXX. Payment is NOT dependent on your answers to the following background questions on country and language.\n</p>"}],

	["q_intro_country", "Question", {q:"What country are you from?", as:["USA", "Canada", "UK", "Australia", "New Zealand", "India", "Other"], hasCorrect:0, randomOrder:false}],

	["q_intro_language", "Question", {q:"Is English your first language?", as:["Yes", "No"], hasCorrect:0, randomOrder:false}],

	["q_intro_age", "Question", {q:"What is your age bracket?", as:["18-24", "25-34", "35-49", "50-70", "70+"], hasCorrect:0, randomOrder:false}],

	["end-experiment", "Message", {html: "<p>End of experiment. Thank you for participating in this study!</p><p>Your completion code is: <b>XXXXXX</b></p><p>Please copy and paste this code into the Prolific survey to receive your payment.</p><p>Click the button below to submit your data to the server.</p>", transfer: "Submit and end experiment"}],

	["intro-gram", "Message", {html: "<p>For this experiment, please place your left index finger on the 'e' key and your right index finger on the 'i' key.</p><p> You will read sentences word by word. On each screen you will see two options: one will be the next word in the sentence, and one will not. Select the word that continues the sentence by pressing 'e' (left-hand) for the word on the left or pressing 'i' (right-hand) for the word on the right.</p><p>Select the best word as quickly as you can, but without making too many errors.</p>"}],
	["intro-practice", "Message", {html: "The following items are for practice." }],
	["end-practice", "Message", {html: "End of practice. The experiment will begin next."}],
	["sep", "MazeSeparator", {normalMessage: "Correct! Press any key to continue", errorMessage: "Incorrect! Press any key to continue."}],
	["done", "Message", {html: "All done!"}],

	[["practice", 108], "Maze", {s:"The semester will start next week, but the students and teachers are not ready.", a:"x-x-x chivalry anti wages body sold, sin sky entitled sky concrete oil him goods."}],
	[["practice", 107], "Maze", {s:"The mother of the prisoner sent him packages that contained cookies and novels.", a:"x-x-x placed dry arm amounted rare nor rhythmic fund authority blossom me defect."}],
	//[["practice", 105], "Maze", {s:"The reporter had dinner yesterday with the baseball player who Kevin admired.", a:"x-x-x invested joy reduce organisms rise sum attained tended sin Troop flowing."}],
	//[["practice", 104], "Maze", {s:"The therapist set up a meeting with the upset woman and her husband yesterday.", a:"x-x-x socialism ten sit sum absence wave ran keeps exist dry sum settled remainder."}],

	// [["crit_item", 1], "Maze", {s:"Kim will display the photos she took next month, but she won't show all of them.", a:"x-x-x milk dealing sit compel eat thin poem older, us thy scale soft ran eat soon."}],
	// [["crit_item", 2], "Maze", {s:"Greta will display the photos she took last month, but she won't show all of them.", a:"x-x-x milk dealing sit compel eat thin poem older, us thy scale soft ran eat soon."}],
	// [["crit_item", 3], "Maze", {s:"Kim will display the photos she took next month, but she won't show all of them.", a:"x-x-x milk dealing sit compel eat thin poem older, us thy scale soft ran eat soon."}],

	[["crit_item", '1048'], "Maze", {s:"Played from and unified by Amazon.", a:"x-x-x lose grow octopus sir Guilty."}],
	[["crit_item", '1068'], "Maze", {s:"Nasser sighed, apparently weighing the same..", a:"x-x-x bikers, parameters dividend tell hear.."}],
	[["crit_item", '1593'], "Maze", {s:"Two thousand inherited a month, aug.", a:"x-x-x download therapist glad rates, des."}],



	//
	// [["crit_item", '1555'], "Maze", {s:"POWDER ROOM Ricardo Sat foul Notre.", a:"x-x-x OKAY Fittest Math riot Widen."}],
	// [["crit_item", '1591'], "Maze", {s:"Thank spawned for Arc this Ven.", a:"x-x-x plagued west Inn lady Avg."}],
	// [["crit_item", '1048'], "Maze", {s:"Played from and unified by Amazon.", a:"x-x-x lose grow octopus sir Guilty."}],
	// [["crit_item", '1068'], "Maze", {s:"Nasser sighed, apparently weighing the same..", a:"x-x-x bikers, parameters dividend tell hear.."}],
	// [["crit_item", '1730'], "Maze", {s:"Duderstadt in the Eichsfeld tattoos pred.", a:"x-x-x sir glad Abrogated screwed loam."}],
	// [["crit_item", '1736'], "Maze", {s:"You ask for a 50. Nab.", a:"x-x-x lake knew cent en. Pomp."}],
	// [["crit_item", '1561'], "Maze", {s:"Wars SELECT any revised wretched, really?", a:"x-x-x CLOSET jack expired worsened, happen?"}],
	// [["crit_item", '1032'], "Maze", {s:'Triangular silver plastic, "NEWSTART PE-TA-PUN A.V.C."', a:'x-x-x miller ongoing, "OPERANDS WATERSHED OBOES."'}],


];

// ITEMS WITH PUNCTUATION FROM D SET
// [["crit_item", '1555'], "Maze", {s:"POWDER ROOM Ricardo Sat foul Notre.", a:"x-x-x OKAY Fittest Math riot Widen."}],
// [["crit_item", '1591'], "Maze", {s:"Thank spawned for Arc this Ven.", a:"x-x-x plagued west Inn lady Avg."}],
// [["crit_item", '1048'], "Maze", {s:"Played from and unified by Amazon.", a:"x-x-x lose grow octopus sir Guilty."}],
// [["crit_item", '1068'], "Maze", {s:"Nasser sighed, apparently weighing the same..", a:"x-x-x bikers, parameters dividend tell hear.."}],
// [["crit_item", '1730'], "Maze", {s:"Duderstadt in the Eichsfeld tattoos pred.", a:"x-x-x sir glad Abrogated screwed loam."}],
// [["crit_item", '1736'], "Maze", {s:"You ask for a 50. Nab.", a:"x-x-x lake knew cent en. Pomp."}],
// [["crit_item", '1561'], "Maze", {s:"Wars SELECT any revised wretched, really?", a:"x-x-x CLOSET jack expired worsened, happen?"}],
// [["crit_item", '1032'], "Maze", {s:"Triangular silver plastic, "NEWSTART PE-TA-PUN A.V.C."", a:"x-x-x miller ongoing, "OPERANDS WATERSHED OBOES.""}],
// [["crit_item", '1250'], "Maze", {s:"For OPEN HOUSE, Chris Huntington, CNN.", a:"x-x-x MISS THANK, Bunch Negligible, OVEN."}],
// [["crit_item", '1091'], "Maze", {s:"Gift garage plot magi sentence abb.", a:"x-x-x brutal dare jure republic dike."}],
// [["crit_item", '1573'], "Maze", {s:"Truth'm not prices with his favorable.", a:"x-x-x jack server mind knew underwent."}],
// [["crit_item", '1169'], "Maze", {s:"Currency Converter: Currency XE: Convert MYREUR.", a:"x-x-x Disabling: Interact OBOE: Happily FLEDGE."}],
// [["crit_item", '1120'], "Maze", {s:"Luke91 help pump to 0.20 ok??", a:"x-x-x okay oven cent opus sir??"}],
// [["crit_item", '1067'], "Maze", {s:"Related Post "Plumbing San Bernardino Ca"", a:"x-x-x Wait "Brightly Ford Groundwork Sick""}],
// [["crit_item", '1556'], "Maze", {s:"ITNESS CALL people who are Dug.", a:"x-x-x OKAY forget jack yeah Sync."}],
// [["crit_item", '1190'], "Maze", {s:"Concrete Patio Cost. Outdoor Patio and.", a:"x-x-x Avian Glad. Runners Avail sir."}],
// [["crit_item", '1685'], "Maze", {s:"We have thyroid to worry PRE.", a:"x-x-x luck drinker east scary TRIP."}],
// [["crit_item", '1540'], "Maze", {s:"Beckel wants every neurological I've TRAN.", a:"x-x-x worse weird transformers Guys GAGS."}],
// [["crit_item", '1143'], "Maze", {s:"Shastrinagar, 35 kms, Great Nicobar Is.", a:"x-x-x cent zeal, Worry Backlot Step."}],
// [["crit_item", '1147'], "Maze", {s:"URL as, or review indicating Vimeo.", a:"x-x-x sir, lady senate apocalypse Axles."}],
// [["crit_item", '1544'], "Maze", {s:"Integ mean, let's face the NON.", a:"x-x-x okay, trump anti fund KNEW."}],
// [["crit_item", '1563'], "Maze", {s:"Umbilical cord blood transplantation is MID.", a:"x-x-x dent proud interchangeably sir JACK."}],
// [["crit_item", '1562'], "Maze", {s:"Well, overnight might be his NON.", a:"x-x-x interface trump laws cent APP."}],
// [["crit_item", '1743'], "Maze", {s:"It's Auckland a little bit Bring.", a:"x-x-x Investor pull starts laws Users."}],
// [["crit_item", '1066'], "Maze", {s:"Ezra grunted, stepping over another Com..", a:"x-x-x satiric, blockade wish message Ups.."}],
// [["crit_item", '1625'], "Maze", {s:"Like sustaining, with a secret Quite.", a:"x-x-x safeguards, hour yeah exists Enjoy."}],
// [["crit_item", '1035'], "Maze", {s:"List and UV was a NEIN!", a:"x-x-x god RPM yeah hill URNS!"}],
// [["crit_item", '1593'], "Maze", {s:"Two thousand inherited a month, aug.", a:"x-x-x download therapist glad rates, des."}],
// [["crit_item", '1174'], "Maze", {s:"Any city I trip I ain't....", a:"x-x-x shut yeah wild fact trial...."}],
// [["crit_item", '1202'], "Maze", {s:"Buy sell signals remains a particular.", a:"x-x-x luck dynasty passion cent interviews."}],
// [["crit_item", '1180'], "Maze", {s:"More "Free football picks week 13"", a:"x-x-x "Jack grateful messy lord bed""}],
// [["crit_item", '1557'], "Maze", {s:"Steven's going to make it COMM.", a:"x-x-x maybe jack cent bill WATT."}],
// [["crit_item", '1234'], "Maze", {s:"Home What's On Stage MAMMA MIA!", a:"x-x-x Wonder Jack Bunch SYNOD FEUD!"}],
// [["crit_item", '1693'], "Maze", {s:"Trade Secret Touch sector inflict MediumS.", a:"x-x-x Senate Frank fiscal sensual Locates."}],
// [["crit_item", '1596'], "Maze", {s:"Conf washing Piet with that MAY.", a:"x-x-x easiest Oust loss yeah HEAR."}],
// [["crit_item", '1129'], "Maze", {s:"Don't think twice, use Probate Advance!!", a:"x-x-x floor yards, cent Scouted Discuss!!"}],
// [["crit_item", '1528'], "Maze", {s:"ARK is Kat going to IND.", a:"x-x-x okay Lows store cent OPUS."}],
// [["crit_item", '1005'], "Maze", {s:"Domain Wikileaks gone: access is NOT..", a:"x-x-x Statesman glad: gotten al DAD.."}],
// [["crit_item", '1652'], "Maze", {s:"I came into this process divor.", a:"x-x-x ways fund goes compare copra."}],
// [["crit_item", '1612'], "Maze", {s:"Compulsively, with GeForce those by regret.", a:"x-x-x cent Disband thank yeah assure."}],
// [["crit_item", '1577'], "Maze", {s:"There are DW pictures, discrepancy Mit.", a:"x-x-x okay OUST somebody, prerogative Bono."}],
// [["crit_item", '1681'], "Maze", {s:"We melts Member to do Sask.", a:"x-x-x pupil Author okay vs Lain."}],
// [["crit_item", '1718'], "Maze", {s:"So the Compatibility is captcha jurisd.", a:"x-x-x cup Characterised mid troupes revues."}],
// [["crit_item", '1214'], "Maze", {s:"Open crate for airhorn, signifying endex.", a:"x-x-x frail glad earldom, exonerated sitar."}],
// [["crit_item", '1581'], "Maze", {s:"ENG the beginning of cheesy Guant.", a:"x-x-x sir recommend pre glands Knoll."}],
// [["crit_item", '1580'], "Maze", {s:"IND also very Parks to Highly.", a:"x-x-x hate cent Tooth sir Breath."}],
// [["crit_item", '1546'], "Maze", {s:"Bug course he had to Aust.", a:"x-x-x senate okay jack hill Sacs."}],
// [["crit_item", '1667'], "Maze", {s:"White like, there was no Und.", a:"x-x-x okay, march fun hour Plc."}],
// [["crit_item", '1657'], "Maze", {s:"Production continued for over four Id.", a:"x-x-x ourselves eat hear girl Bowl."}],
// [["crit_item", '1103'], "Maze", {s:"Match cricket suit prediction 100 certain.", a:"x-x-x spirits glad humanities dime divorce."}],

// ITEMS WITHOUT PUNCTUATION FROM D SET
// [["crit_item", '1555'], "Maze", {s:"POWDER ROOM Ricardo Sat foul Notre", a:"x-x-x OKAY Gallant Dirt mist Tutor"}],
// [["crit_item", '1591'], "Maze", {s:"Thank spawned for Arc this Ven", a:"x-x-x ravaged hour Hut sick Bled"}],
// [["crit_item", '1048'], "Maze", {s:"Played from and unified by Amazon", a:"x-x-x lord knew asphalt glad Guilty"}],
// [["crit_item", '1068'], "Maze", {s:"Nasser sighed apparently weighing the same", a:"x-x-x grudge indication headache sir yeah"}],
// [["crit_item", '1730'], "Maze", {s:"Duderstadt in the Eichsfeld tattoos pred", a:"x-x-x okay guys Disavowed cheated muon"}],
// [["crit_item", '1736'], "Maze", {s:"You ask for a 50 Nab", a:"x-x-x lake mid cent en Rims"}],
// [["crit_item", '1561'], "Maze", {s:"Wars SELECT any revised wretched really", a:"x-x-x BUCKET okay tweeted fibrosis please"}],
// [["crit_item", '1032'], "Maze", {s:"Triangular silver plastic NEWSTART PETAPUN AVC", a:"x-x-x miller discuss SEMIARID PLATTED JURE"}],
// [["crit_item", '1250'], "Maze", {s:"For OPEN HOUSE Chris Huntington CNN", a:"x-x-x MISS THANK Idiot Stagnation FLU"}],
// [["crit_item", '1091'], "Maze", {s:"Gift garage plot magi sentence abb", a:"x-x-x tricky pope clot republic nave"}],
// [["crit_item", '1573'], "Maze", {s:"Truthm not prices with his favorable", a:"x-x-x okay bureau jack walk separates"}],
// [["crit_item", '1169'], "Maze", {s:"Currency Converter Currency XE Convert MYREUR", a:"x-x-x Statesman Dreaming GORY Hallway FLEDGE"}],
// [["crit_item", '1120'], "Maze", {s:"Luke91 help pump to 020 ok", a:"x-x-x okay coke ago clef sir"}],
// [["crit_item", '1067'], "Maze", {s:"Related Post Plumbing San Bernardino Ca", a:"x-x-x Wait Temporal Hop Chandelier Luck"}],
// [["crit_item", '1556'], "Maze", {s:"ITNESS CALL people who are Dug", a:"x-x-x OKAY forget jack dad Sync"}],
// [["crit_item", '1190'], "Maze", {s:"Concrete Patio Cost Outdoor Patio and", a:"x-x-x Renal Glad Elderly Squid sir"}],
// [["crit_item", '1685'], "Maze", {s:"We have thyroid to worry PRE", a:"x-x-x ways volcano pre yards HILL"}],
// [["crit_item", '1540'], "Maze", {s:"Beckel wants every neurological Ive TRAN", a:"x-x-x worse worst investigates Gigs TUGS"}],
// [["crit_item", '1143'], "Maze", {s:"Shastrinagar 35 kms Great Nicobar Is", a:"x-x-x dumb rook Thank Cantata Sure"}],
// [["crit_item", '1147'], "Maze", {s:"URL as or review indicating Vimeo", a:"x-x-x okay hear finals millennium Visor"}],
// [["crit_item", '1544'], "Maze", {s:"Integ mean lets face the NON", a:"x-x-x okay urge jack anti SIR"}],
// [["crit_item", '1563'], "Maze", {s:"Umbilical cord blood transplantation is MID", a:"x-x-x vain proud interchangeable glad JACK"}],
// [["crit_item", '1562'], "Maze", {s:"Well overnight might be his NON", a:"x-x-x peninsula trump cent jack APP"}],
// [["crit_item", '1743'], "Maze", {s:"Its Auckland a little bit Bring", a:"x-x-x Praising me starts laws Goals"}],
// [["crit_item", '1066'], "Maze", {s:"Ezra grunted stepping over another Com", a:"x-x-x satiric crescent wear dollars Outs"}],
// [["crit_item", '1625'], "Maze", {s:"Like sustaining with a secret Quite", a:"x-x-x newsletter cent oh decide Miles"}],
// [["crit_item", '1035'], "Maze", {s:"List and UV was a NEIN", a:"x-x-x foot EDGY okay kid YAMS"}],
// [["crit_item", '1593'], "Maze", {s:"Two thousand inherited a month aug", a:"x-x-x darkness stripping oh rates liar"}],
// [["crit_item", '1174'], "Maze", {s:"Any city I trip I aint", a:"x-x-x shut pre wild guy garb"}],
// [["crit_item", '1202'], "Maze", {s:"Buy sell signals remains a particular", a:"x-x-x luck dynasty bedroom kid interviews"}],
// [["crit_item", '1180'], "Maze", {s:"More Free football picks week 13", a:"x-x-x Jack annoying slope cent al"}],
// [["crit_item", '1557'], "Maze", {s:"Stevens going to make it COMM", a:"x-x-x smart jack till oh NOVO"}],
// [["crit_item", '1234'], "Maze", {s:"Home Whats On Stage MAMMA MIA", a:"x-x-x Teddy Glad Meant SYNOD HERS"}],
// [["crit_item", '1693'], "Maze", {s:"Trade Secret Touch sector inflict MediumS", a:"x-x-x Spring Saint hungry corolla Plunger"}],
// [["crit_item", '1596'], "Maze", {s:"Conf washing Piet with that MAY", a:"x-x-x easiest Oust lack know SIR"}],
// [["crit_item", '1129'], "Maze", {s:"Dont think twice use Probate Advance", a:"x-x-x thank yards app Disband Laughed"}],
// [["crit_item", '1528'], "Maze", {s:"ARK is Kat going to IND", a:"x-x-x okay Apes worse took HOC"}],
// [["crit_item", '1005'], "Maze", {s:"Domain Wikileaks gone access is NOT", a:"x-x-x Sarcastic glad suffer sir CENT"}],
// [["crit_item", '1652'], "Maze", {s:"I came into this process divor", a:"x-x-x ways fund goes dollars copra"}],
// [["crit_item", '1612'], "Maze", {s:"Compulsively with GeForce those by regret", a:"x-x-x yeah Forgave thank mom bailey"}],
// [["crit_item", '1577'], "Maze", {s:"There are DW pictures discrepancy Mit", a:"x-x-x sad PLOY somebody retaliation Loom"}],
// [["crit_item", '1681'], "Maze", {s:"We melts Member to do Sask", a:"x-x-x pupil Author lack guy Lain"}],
// [["crit_item", '1718'], "Maze", {s:"So the Compatibility is captcha jurisd", a:"x-x-x cup Characterised sir cargoes revues"}],
// [["crit_item", '1214'], "Maze", {s:"Open crate for airhorn signifying endex", a:"x-x-x ample holy alcalde emboldened curia"}],
// [["crit_item", '1581'], "Maze", {s:"ENG the beginning of cheesy Guant", a:"x-x-x okay ourselves mom reacts Sited"}],
// [["crit_item", '1580'], "Maze", {s:"IND also very Parks to Highly", a:"x-x-x wish lord Beans holy Breath"}],
// [["crit_item", '1546'], "Maze", {s:"Bug course he had to Aust", a:"x-x-x senate okay pre sir Glam"}],
// [["crit_item", '1667'], "Maze", {s:"White like there was no Und", a:"x-x-x rate guess hour cent Cum"}],
// [["crit_item", '1657'], "Maze", {s:"Production continued for over four Id", a:"x-x-x ourselves god yeah laws Lock"}],
// [["crit_item", '1103'], "Maze", {s:"Match cricket suit prediction 100 certain", a:"x-x-x nowhere glad humanities dime husband"}],

